version: '3.4'

services:
  nodeboilerplate:
    image: nodeboilerplate
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production

    env_file: .env
    
    ports:
      - ${PORT}:${PORT}
      # - 3000:3000
